name: pipeline

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    name: quality
    uses: guilhermelinosp/templates/.github/workflows/lib-quality.yml@main
    with:
      go-version-file: go.mod
