name: pr-check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint:
    uses: guilhermelinosp/ci-templates/.github/workflows/shellcheck.yml@main

  commit-lint:
    uses: guilhermelinosp/ci-templates/.github/workflows/commit-lint.yml@main

  merge-check:
    uses: guilhermelinosp/ci-templates/.github/workflows/merge-check.yml@main

  gitleaks:
    uses: guilhermelinosp/ci-templates/.github/workflows/gitleaks.yml@main

  labeler:
    uses: guilhermelinosp/ci-templates/.github/workflows/labeler.yml@main

  gosec:
    uses: guilhermelinosp/ci-templates/.github/workflows/gosec.yml@main
    with:
      dir: ./...

  go-test:
    uses: guilhermelinosp/ci-templates/.github/workflows/go-test.yml@main

  golangci:
    uses: guilhermelinosp/ci-templates/.github/workflows/golangci.yml@main
