name: pr-check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint:
    uses: guilhermelinosp/templates/.github/workflows/shellcheck.yml@e7d093b460c1e25f16121d509eefcbb597612c95 # main

  merge-check:
    uses: guilhermelinosp/templates/.github/workflows/merge-check.yml@fde7d4a5a2e7aa5dd42e8812df4783daa39b1543 # main

  gitleaks:
    uses: guilhermelinosp/templates/.github/workflows/gitleaks.yml@e7d093b460c1e25f16121d509eefcbb597612c95 # main

  labeler:
    uses: guilhermelinosp/templates/.github/workflows/labeler.yml@e7d093b460c1e25f16121d509eefcbb597612c95 # main

  quality:
    name: quality
    uses: guilhermelinosp/templates/.github/workflows/lib-quality.yml@e7d093b460c1e25f16121d509eefcbb597612c95 # main
    with:
      go-version-file: go.mod
